apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: smartbch
    version: 0.6.1
    deploy: smartbch-2
  name: smartbch-secondary
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      service: smartbch
      deploy: smartbch-2
  template:
    metadata:
      labels:
        service: smartbch
        deploy: smartbch-2
    spec:
      containers:
      - args:
        - start
        - --mainnet-genesis-height=698502
        - --https.addr=off
        - --wss.addr=off
        - --skip-sanity-check
        - --log_level=error
        - --no-bch-client
        command:
        - smartbchd
        image: smartbch/smartbchd:v0.6.1
        imagePullPolicy: Always
        name: smartbch
        volumeMounts:
          - mountPath: /root/.smartbchd
            name: smartbch-secondary-data
        resources:
          requests:
            memory: "9Gi"
          limits:
            memory: "9Gi"
        ports:
          - name: api
            containerPort: 8545
          - name: websocket
            containerPort: 8546
          - name: peer
            containerPort: 27656
      restartPolicy: Always
      terminationGracePeriodSeconds: 600
      volumes:
        - name: smartbch-secondary-data
          gcePersistentDisk:
            pdName: smartbch-secondary-data
            fsType: ext4
