apiVersion: batch/v1
kind: Job
metadata:
  name: smartbch-init-testnet
spec:
  template:
    metadata:
      name: smartbch-init-testnet
    spec:
      containers:
      - name: smartbch-init-testnet
        image: zquestz/smartbch:latest
        command: ["smartbchd", "init", "freedomMan", "--chain-id", '0x2711']
        volumeMounts:
          - name: smartbch-data
            mountPath: /root/.smartbchd
        resources:
          requests:
            memory: "1Gi"
      restartPolicy: Never
      volumes:
        - name: smartbch-data
          gcePersistentDisk:
            pdName: smartbch-data
            fsType: ext4
