apiVersion: batch/v1
kind: Job
metadata:
  name: smartbch-init
spec:
  template:
    metadata:
      name: smartbch-init
    spec:
      containers:
      - name: smartbch-init
        image: zquestz/smartbch:mainnet
        command: ["smartbchd", "init", "mynode", "--chain-id", "0x2710"]
        volumeMounts:
          - name: smartbch-data
            mountPath: /root/.smartbchd
        resources:
          requests:
            memory: "1Gi"
      restartPolicy: Never
      volumes:
        - name: smartbch-data
          gcePersistentDisk:
            pdName: smartbch-data
            fsType: ext4
